# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Sender(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, email_address: str=None, name: str=None):  # noqa: E501
        """Sender - a model defined in Swagger

        :param email_address: The email_address of this Sender.  # noqa: E501
        :type email_address: str
        :param name: The name of this Sender.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'email_address': str,
            'name': str
        }

        self.attribute_map = {
            'email_address': 'email_address',
            'name': 'name'
        }

        self._email_address = email_address
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'Sender':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Sender of this Sender.  # noqa: E501
        :rtype: Sender
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email_address(self) -> str:
        """Gets the email_address of this Sender.


        :return: The email_address of this Sender.
        :rtype: str
        """
        return self._email_address

    @email_address.setter
    def email_address(self, email_address: str):
        """Sets the email_address of this Sender.


        :param email_address: The email_address of this Sender.
        :type email_address: str
        """

        self._email_address = email_address

    @property
    def name(self) -> str:
        """Gets the name of this Sender.


        :return: The name of this Sender.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Sender.


        :param name: The name of this Sender.
        :type name: str
        """

        self._name = name
