---
swagger: "2.0"
info:
  description: "Email API for ZeroWing Event Management System."
  version: "1.0.0"
  title: "Email API"
host: "localhost:8083"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /email:
    post:
      tags:
      - "Email"
      summary: "Used to send an Email."
      operationId: "send_email"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Email object containing the Email details."
        required: true
        schema:
          $ref: "#/definitions/Email"
      responses:
        "200":
          description: "Email Sent."
          schema:
            $ref: "#/definitions/Email"
        "400":
          description: "Invalid input."
          schema:
            $ref: "#/definitions/InvalidInputError"
        "500":
          description: "Unexpected failure in the service layer."
          schema:
            $ref: "#/definitions/UnexpectedServiceError"
      x-swagger-router-controller: "swagger_server.controllers.email_controller"
    options:
      tags:
      - "Email"
      summary: "Used to respond to browser with Access-Control-Allow-Methods header.\
        \ Required for POST."
      operationId: "send_email_options"
      parameters: []
      responses:
        "200":
          description: "Response headers will indicate the allowable methods."
      x-swagger-router-controller: "swagger_server.controllers.email_controller"
definitions:
  Email:
    type: "object"
    properties:
      email_subject:
        type: "string"
        example: "Hello World!"
      email_content:
        type: "string"
        example: "Heya! Please work"
      email_from:
        type: "object"
        example:
          email_address: "eventastic@gmail.com"
          name: "EvenTastic"
        allOf:
        - $ref: "#/definitions/Sender"
      email_to:
        type: "array"
        items:
          $ref: "#/definitions/Receiver"
    example:
      email_to:
      - email_address: "bob@gmail.com"
        name: "Bob"
      - email_address: "bob@gmail.com"
        name: "Bob"
      email_content: "Heya! Please work"
      email_subject: "Hello World!"
      email_from:
        email_address: "eventastic@gmail.com"
        name: "EvenTastic"
  Receiver:
    type: "object"
    properties:
      email_address:
        type: "string"
        example: "bob@gmail.com"
      name:
        type: "string"
        example: "Bob"
    example:
      email_address: "bob@gmail.com"
      name: "Bob"
  Sender:
    type: "object"
    properties:
      email_address:
        type: "string"
      name:
        type: "string"
  Error:
    type: "object"
    properties:
      code:
        type: "string"
      type:
        type: "string"
      message:
        type: "string"
  InvalidInputError:
    allOf:
    - $ref: "#/definitions/Error"
    - {}
    example:
      code: 400
      type: "InvalidInputError"
      message: "The following mandatory fields were not provided: %field_name_1%,\
        \ %field_name_2%"
  UnexpectedServiceError:
    allOf:
    - $ref: "#/definitions/Error"
    - {}
    example:
      code: 500
      type: "UnexpectedServiceError"
      message: "The following unexpected runtime error has occurred: %error%"
