# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Seating(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, seating_type: str=None, seating_number: int=None):  # noqa: E501
        """Seating - a model defined in Swagger

        :param seating_type: The seating_type of this Seating.  # noqa: E501
        :type seating_type: str
        :param seating_number: The seating_number of this Seating.  # noqa: E501
        :type seating_number: int
        """
        self.swagger_types = {
            'seating_type': str,
            'seating_number': int
        }

        self.attribute_map = {
            'seating_type': 'seating_type',
            'seating_number': 'seating_number'
        }

        self._seating_type = seating_type
        self._seating_number = seating_number

    @classmethod
    def from_dict(cls, dikt) -> 'Seating':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Seating of this Seating.  # noqa: E501
        :rtype: Seating
        """
        return util.deserialize_model(dikt, cls)

    @property
    def seating_type(self) -> str:
        """Gets the seating_type of this Seating.


        :return: The seating_type of this Seating.
        :rtype: str
        """
        return self._seating_type

    @seating_type.setter
    def seating_type(self, seating_type: str):
        """Sets the seating_type of this Seating.


        :param seating_type: The seating_type of this Seating.
        :type seating_type: str
        """

        self._seating_type = seating_type

    @property
    def seating_number(self) -> int:
        """Gets the seating_number of this Seating.


        :return: The seating_number of this Seating.
        :rtype: int
        """
        return self._seating_number

    @seating_number.setter
    def seating_number(self, seating_number: int):
        """Sets the seating_number of this Seating.


        :param seating_number: The seating_number of this Seating.
        :type seating_number: int
        """

        self._seating_number = seating_number
