# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.seating import Seating
from swagger_server import util


class Venue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, venue_id: int=None, venue_name: str=None, venue_desc: str=None, venue_img: str=None, venue_address: str=None, seating: List[Seating]=None):  # noqa: E501
        """Venue - a model defined in Swagger

        :param venue_id: The venue_id of this Venue.  # noqa: E501
        :type venue_id: int
        :param venue_name: The venue_name of this Venue.  # noqa: E501
        :type venue_name: str
        :param venue_desc: The venue_desc of this Venue.  # noqa: E501
        :type venue_desc: str
        :param venue_img: The venue_img of this Venue.  # noqa: E501
        :type venue_img: str
        :param venue_address: The venue_address of this Venue.  # noqa: E501
        :type venue_address: str
        :param seating: The seating of this Venue.  # noqa: E501
        :type seating: List[Seating]
        """
        self.swagger_types = {
            'venue_id': int,
            'venue_name': str,
            'venue_desc': str,
            'venue_img': str,
            'venue_address': str,
            'seating': List[Seating]
        }

        self.attribute_map = {
            'venue_id': 'venue_id',
            'venue_name': 'venue_name',
            'venue_desc': 'venue_desc',
            'venue_img': 'venue_img',
            'venue_address': 'venue_address',
            'seating': 'seating'
        }

        self._venue_id = venue_id
        self._venue_name = venue_name
        self._venue_desc = venue_desc
        self._venue_img = venue_img
        self._venue_address = venue_address
        self._seating = seating

    @classmethod
    def from_dict(cls, dikt) -> 'Venue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Venue of this Venue.  # noqa: E501
        :rtype: Venue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def venue_id(self) -> int:
        """Gets the venue_id of this Venue.


        :return: The venue_id of this Venue.
        :rtype: int
        """
        return self._venue_id

    @venue_id.setter
    def venue_id(self, venue_id: int):
        """Sets the venue_id of this Venue.


        :param venue_id: The venue_id of this Venue.
        :type venue_id: int
        """

        self._venue_id = venue_id

    @property
    def venue_name(self) -> str:
        """Gets the venue_name of this Venue.


        :return: The venue_name of this Venue.
        :rtype: str
        """
        return self._venue_name

    @venue_name.setter
    def venue_name(self, venue_name: str):
        """Sets the venue_name of this Venue.


        :param venue_name: The venue_name of this Venue.
        :type venue_name: str
        """

        self._venue_name = venue_name

    @property
    def venue_desc(self) -> str:
        """Gets the venue_desc of this Venue.


        :return: The venue_desc of this Venue.
        :rtype: str
        """
        return self._venue_desc

    @venue_desc.setter
    def venue_desc(self, venue_desc: str):
        """Sets the venue_desc of this Venue.


        :param venue_desc: The venue_desc of this Venue.
        :type venue_desc: str
        """

        self._venue_desc = venue_desc

    @property
    def venue_img(self) -> str:
        """Gets the venue_img of this Venue.


        :return: The venue_img of this Venue.
        :rtype: str
        """
        return self._venue_img

    @venue_img.setter
    def venue_img(self, venue_img: str):
        """Sets the venue_img of this Venue.


        :param venue_img: The venue_img of this Venue.
        :type venue_img: str
        """

        self._venue_img = venue_img

    @property
    def venue_address(self) -> str:
        """Gets the venue_address of this Venue.


        :return: The venue_address of this Venue.
        :rtype: str
        """
        return self._venue_address

    @venue_address.setter
    def venue_address(self, venue_address: str):
        """Sets the venue_address of this Venue.


        :param venue_address: The venue_address of this Venue.
        :type venue_address: str
        """

        self._venue_address = venue_address

    @property
    def seating(self) -> List[Seating]:
        """Gets the seating of this Venue.


        :return: The seating of this Venue.
        :rtype: List[Seating]
        """
        return self._seating

    @seating.setter
    def seating(self, seating: List[Seating]):
        """Sets the seating of this Venue.


        :param seating: The seating of this Venue.
        :type seating: List[Seating]
        """

        self._seating = seating
